---
- name: Configuring global settings.
  lineinfile:
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: present
  with_items: "{{ postgresql_global_config_options }}"
  notify: restart postgresql

- name: Configuring host based authentication.
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql
