---
- name: Setting PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  notify: restart postgresql

- name: Creating systemd override directories if it does not exists.
  file:
    path: /etc/systemd/system/postgresql.service.d
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Setting PostgreSQL systemd overrides.
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/postgresql.service.d/override.conf
    mode: 0644

- name: Creating directories if it does not exists.
  file:
    path: "{{ item }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0750
  loop: "{{ postgresql_dirs|flatten(levels=1) }}"

- name: Changing home directory for user.
  user:
    name: "{{ postgresql_user }}"
    home: "{{ postgresql_data_dir | regex_replace('/\\w+$', '') }}"

- name: Checking if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Initializing PostgreSQL database.
  command: "initdb -D {{ postgresql_data_dir }} --data-checksums"
  when: not pgdata_dir_version.stat.exists
  become_user: "{{ postgresql_user }}"
