---

# Installing PostgreSQL
- import_tasks: install.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

# Initializing PostgreSQL
- import_tasks: initialize.yml

# Configuring PostgreSQL
- import_tasks: configure.yml

- name: Set enabled|disabled for service.
  service:
    name: postgresql
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
#- import_tasks: users.yml
#- import_tasks: databases.yml
