---

# Installing PostgreSQL
- import_tasks: install.yml
  become: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

# Initializing PostgreSQL
- import_tasks: initialize.yml
  become: yes

#- include_tasks: configure.yml

#- name: Ensure PostgreSQL is started and enabled on boot.
#  service:
#    name: "{{ postgresql_daemon }}"
#    state: "{{ postgresql_service_state }}"
#    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
#- import_tasks: users.yml
#- import_tasks: databases.yml
