---

# Install PostgreSQL
- include_tasks: install.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

# Initialize PostgreSQL
- include_tasks: initialize.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

# Configure PostgreSQL
- include_tasks: configure.yml

- name: Set enabled|disabled for service.
  service:
    name: postgresql
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Create users.
- include_tasks: users.yml

# Create dbs.
- include_tasks: databases.yml

# Set privileges.
#- include_tasks: privileges.yml
