---
- name: Creating postgresql users.
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: yes
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  become_user: "{{ postgresql_user }}"
  no_log: yes
